### ISSUE TITLE
当txt文件开头不是章节名称是会报错

### ISSUE THREAD

**Issue by elysia-best** [ganyuanzhen/TXT-Automatic-Chaptering#7]
Traceback (most recent call last):
  File "D:\Users\15228\miniconda3\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Projects\TXT-Automatic-Chaptering\core\gui.py", line 129, in all_in_one
    split_txt(
  File "D:\Projects\TXT-Automatic-Chaptering\core\utils.py", line 59, in split_txt
    save_file.write(line)
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by elysia-best** [comment]
该问题将在新版本中处理，Python版本将不再更新

**Comment by elysia-best** [comment]
fixed
